### ISSUE TITLE
Add support for 3rd party map geometries

### ISSUE THREAD

**Issue by systemcatch** [tmrowco/electricitymap#840] opened 2017-11-08 12:03 UTC
@corradio @brunolajoie @BrianCraig 
There's issues open at the moment which are blocked due to not having shapes available from the natural earth file we use.  

Several of Chile's regions have duplicate hasc and fips codes so cannot be mapped with the functions currently in countrytopos.js. #821.  @jarek has also said that there will be similar problems with the Philippines.  

The Canary Islands are represented as one feature in natural earth.  To split them individually will require either extracting the shapes from natural earth or creating our own geojson for each island. #626  

The USA needs to be split into it's component grid regions which are quite intricate and overlapping.  We will have to import the geojson from elsewhere or create it ourselves. #143 #787 

So as I see it we need to do 2 things.  Allow the use of other identifiers from natural earth, and allow the use of other shape/geojson files.  However I'm not really a frontend person so discussion on how best to implement this is needed.  Realistically the first thing seems much easier to do.

**Comment by corradio** [comment] 2017-11-08 13:17
Hi @systemcatch ,

The `topogen.sh` script contains everything you need to add another identifier.
Ping me on Slack if you need help for understanding the script.

The next step would probably be to merge countryTopos.js into topogen.sh, in order to generate the topology files at compile-time rather than runtime.

Olivier

**Comment by jarek** [comment] 2017-11-08 13:34
In some cases (like Canary Islands, Greek islands, or the King Island) the Natural Earth shapefiles do not have required data precision. So we'll need some other sources in addition to topogen transforming Natural Earth, regardless of which ID we use.

**Comment by systemcatch** [comment] 2017-11-11 12:36
topogen.sh has now been modified to provide adm1_code and region_cod as usable identifiers.  Next step is to create some new functions in countrytopos.js to allow us to get states by them.

**Comment by corradio** [comment] 2017-11-12 12:38
I'm renaming this issue to focus on adding support for 3rd party geometries.

**Comment by corradio** [comment] 2017-12-14 14:32
Duplicate of #913

**Closed by corradio** 2017-12-14 14:32 UTC
Labels: frontend, help wanted
