### ISSUE TITLE
Add Feature / Iceland

### ISSUE THREAD

**Issue by Pantkowsky** [tmrowco/electricitymap#140] opened 2016-11-19 20:33 UTC

**Comment by Pantkowsky** [comment] 2016-11-19 20:34
https://askjaenergy.com/iceland-introduction/energy-data/

**Comment by birkir** [comment] 2016-12-28 15:36
Realtime energy transmission [1], something like this should do the trick (sorry, am more comfortable with js):

```js
async getTotalPowerFlow() {
  const req = await fetch('http://amper.landsnet.is/MapData/api/measurements');
  const data = await req.json();
  return data.find(item => item.key === 'TOTAL_POWER_FLOW').MW;
}
```

We don't share power with other countries.

(2015) [2]
 - Hydro: 13.781 GW (73,3%)
 - Thermal: 5.003 GW (26,6%)
 - Wind: 11 GW (0,05%)
 - Gas: 3.9 GW (0,02%)

(2014) [3]
 - Hydro: 12.872 GW (71,03%)
 - Thermal: 5.238 GW (28,91%)
 - Wind: 8.127 MW (0,04%)
 - Gas: 2,4 GW (0,01%)


[1] http://landsnet.is/english/transmissionandmarket/systemoperations/currentpower/
[2] http://www.orkustofnun.is/media/upprunaabyrgdir/Sto%CC%88dlud-yfirly%CC%81sing-fyrir-2015.pdf
[3] http://www.orkustofnun.is/orkustofnun/frettir/nr/1645

**Comment by corradio** [comment] 2017-01-12 12:48
Hello @birkir 

Sorry for the late reply. It seems like the data source you have given does not discriminate between production types. Am I right or did I misunderstand something?

Thanks,

Olivier

**Comment by birkir** [comment] 2017-01-12 15:38
You are right, I thought using constant ratios of production types *times* the total power flow would give an estimate, but after some thinking, that's not a good idea.

On the other hand, Iceland is really small and there are only 17 power stations [1] in total, which we have all the data on flow, so if I map each power station to production type we have it real, realtime.

On the realtime map the gear/cog icons represent a power station feeding electricity into the grid.

[1] http://www.landsvirkjun.com/company/powerstations/

**Comment by corradio** [comment] 2017-01-12 15:42
Sounds good. Would you be able to write such a parser? I can provide the necessary help but the script itself, in python, should be fairly simple. See for example the parser for EE: https://github.com/corradio/electricitymap/blob/master/feeder/parsers/EE.py
That's the only thing needed!

**Comment by birkir** [comment] 2017-01-12 16:32
Allright, I'll convert my js code to python over the weekend, posting this as a reference for that work.

```js
const stations = [
  { key: 'KRAFLA_F', type: 'geo' },
  { key: 'FLJOTSDA', type: 'hydro' },
  { key: 'LAXA_F', type: 'hydro' },
  { key: 'LAGARF', type: 'hydro' },
  { key: 'BLANDA_F', type: 'hydro' },
  { key: 'MJOLKA', type: 'hydro' },
  { key: 'SULTAR_F', type: 'hydro' },
  { key: 'HRAUN_F', type: 'hydro' },
  { key: 'SIG_F', type: 'hydro' },
  { key: 'VAF', type: 'hydro' },
  { key: 'BURF_F', type: 'hydro' },
  { key: 'KOLVID', type: 'geo' },
  { key: 'IRAFOS_F', type: 'hydro' },
  { key: 'LJOSIF_F', type: 'hydro' },
  { key: 'X_NESJAV', type: 'geo' },
  { key: 'REY', type: 'geo' },
  { key: 'SVA', type: 'geo' },
  { key: 'BUDAR_0', type: 'hydro' }
];

async fetchProduction() {
  const req = await fetch('http://amper.landsnet.is/MapData/api/measurements');
  const data = await req.json();
  const powerflow = data.find(item => item.key === 'TOTAL_POWER_FLOW').MW;
  const datetime = new Date(powerflow.time);
  const production = {};
  const consumption = {};
  production.unknown = totalPower;
  stations.forEach(({ key, type }) => {
    const items = data.filter(item => item.substation === key);
    const mw = Number(items.map(st => st.MW).reduce((a, b) => a + b)) || 0;
    production.unknown -= mw;
    production[type] = (production[type] || 0) + mw;
  });

  return {
    countryCode: 'IS',
    source: 'landsnet.is',
    datetime,
    production,
    consumption,
  };
}
```

**Comment by birkir** [comment] 2017-01-12 16:44
See update above, but is it correct to assume that the consuming is about ~85% of the production?

**Comment by corradio** [comment] 2017-01-12 17:08
I'd rather not return any consumption data because that 85% can vary. So I'd suggest only return production mix for now.

**Comment by birkir** [comment] 2017-01-12 17:18
Ok, I actually calculated 85% from total power flow (through the power grid) divided by the sum of production (hydro, geothermal).

But only production is allright with me 👍

**Comment by corradio** [comment] 2017-01-15 14:06
@birkir how is it going? Need help?

**Comment by brunolajoie** [comment] 2017-02-04 18:28
Hello @birkir thanks a lot for your help!

I'm noticing a mismatch between power capacities and power production from the API, would you happen to know what it could be?

For instance, the BURF_F hydro power plant has a capacity of 6*45=270MW http://www.landsvirkjun.com/Company/PowerStations/BurfellPowerStation

But on http://amper.landsnet.is/MapData/api/measurements we have 6 values for each turbine, summing up to 394MW right now (04/02/17 19h28 GMT+1)

Given that the capacity figures have been double checked in various websites, i'm rather confident that the issue comes from the amper.landsnet.is API, but don't know why

**Comment by corradio** [comment] 2017-02-04 18:51
Realtime transmission map seen here:
http://landsnet.is/english/transmissionandmarket/systemoperations/
Potential contact:

Íris Baldursdóttir
System Operations
Gylfaflöt 9, 112 Reykjavík
iris@landsnet.is
Tel: (+354) 563 9446

**Comment by corradio** [comment] 2017-02-05 10:05
Sent an email to Iris

**Comment by kristjanbb** [comment] 2017-03-03 01:43
Hey @brunolajoie

The issue isn't with the API being incorrect, but the interpretation is incorrect. These numbers do not represent power from plants, but rather these numbers almost all (others data points being total and intersects) represent transmission lines connecting adjacent substations.

You can see how the data is used here: http://landsnet.is/raforkukerfid/kerfisstjornun/aflflutningurnuna/ (note that the english version doesn't show correct data at all and has been broken for a while).

For example Burfell is the almost octopus with 7 transmission lines near the center. As you see summing the lines is rather meaningless since much of the power is just flowing through the substation. This data has few more annoying flaws like even though it's all edges (transmission lines) it only list one of the node (power stations) seemingly at random. Hence the 7th feeding line for Burfell isn't account for.

I'm afraid that this API just isn't very good for getting separate numbers for geothermal / hydro power.

I see two workarounds. One method I speculate works by getting a fairly good approximation for the much fewer geothermal stations and subtract it from the total to get the hydro power.

Another workaround is to fix up the data more. Make sure that all lines are accounted for with correct direction for every node. For example if the 7th line to Burfell had been account for and feeding line "Sigoldulina 3" (SIG_F key SI3) had been subtracted you probably get correct number for Burfell.

Finally check that the sum of geo + hydro adds up to the given total.

**Comment by corradio** [comment] 2017-03-03 07:30
Thanks @kristjanbb for the clarification.
Do you know if / how we can get a real-time API in order to show Iceland on our map?

**Comment by brunolajoie** [comment] 2017-03-03 08:57
Ahhhh that why! Thanks for the clarification! As for your two workaround options:
- Your suggested option 1 is unfortunately not a viable option for us, we prefer a lack of data than estimated data, in order to keep pushing TSO to disclose their their data. 
- Unfortunately, we lack a bit of time to go deeper into option 2 by ourselve right now. If you are willing to help build a valid parser and contribute to extend the map, do not hesitate! We can help with the coding part.
Thanks,

Bruno

**Comment by birkir** [comment] 2017-03-03 11:29
Hi guys, I have not found the time to convert it to python, and make adjustments based on peoples great answers in this thread!

If we can decide on going for option two (which is pretty much the same as I did in JS, with small adjustments), we should go forward with it.

**Comment by kristjanbb** [comment] 2017-03-03 15:22
No sorry @corradio I don't know of any other API public, but I did send an inquiry to Landsnet about this. They might not have all the information reliably broken down since they run the high voltage transmission grid, not production.

**Comment by corradio** [comment] 2017-05-16 09:49
@kristjanbb did you get any reply?

**Comment by kristjanbb** [comment] 2017-05-20 22:11
@corradio nothing useful, just that they would forward it to the right people.

**Comment by corradio** [comment] 2017-05-21 16:24
OK. Any chance we will get a reply? Can we nudge them somehow?

**Comment by kristjanbb** [comment] 2017-05-21 20:58
@corradio Chance of reply? I doubt it, probably buried in pile of dead suggestions now.

Nudge them? Absolutely. There is landsnet@landnet.is, that probably ends in worlds slowest support desk, but doesn't hurt. On Landsnet contact page one can pretty much reach anyone directly via email, but who do you want to contact? You can reach the technical people directly, but they probably don't have the authority to add this functionality. Then your best bet is to sell this idea to management directly, but I'm not confortable with acting as a spoke person of this site to sell this idea.

Finally you can try and ping the producers (Landsvirkjun, 76% of production, Orkuveita Reykjavíkur, RARIK, and Hitaveita Suðurnesja). In fact I'm not even sure if Landsnet (a distributor and not a producer) has the exact breakdown to start with?

**Comment by corradio** [comment] 2017-05-22 07:36
I'll try to nudge them.

**Comment by corradio** [comment] 2018-03-15 07:24
There's quite a few interesting data here:
- https://www.landsvirkjun.com/researchdevelopment/environmentalmonitoring
- https://www.landsvirkjun.com/researchdevelopment/research/windpower/realtimedata/

**Comment by alixunderplatz** [comment] 2018-05-02 20:15
@jarek good that you mentioned this here! 👍 
I also assume these are placeholders for direction and speed.

Many of the 95 values will also show "30 MW" all the time and then all of a sudden they change to something like 4.xx, always starting with a 4.
_ _ _ _

On my way to get some general data on grid load, I found an interesting study which you can download here:
http://energy.mit.edu/publication/electricity-security-supply-iceland/

Looks like they used grid data for 2014 and applied some of the cuts of the "SNIÐ" option [of the map](https://www.landsnet.is/landsnet/flutningskerfid/kerfisstjornun/aflflutningur-nuna/#) (see page 40 of 75 of the document (page 9 of second part)) to perform some grid calculations. 

Consider this as just some "secondary info" as well, nothing that could be used.

**Comment by jarek** [comment] 2018-05-15 08:33
Closing due to no usable data currently available. Please comment or reopen if more data becomes available.

**Closed by jarek** 2018-05-15 08:33 UTC
Labels: data needed, research library

**Comment by alixunderplatz** [comment] 2018-05-15 08:57
@jarek Here's the load profile from the beginning of May when I collected some data:

![image](https://user-images.githubusercontent.com/25743609/40046587-97b42c9a-582d-11e8-89d5-4f020007f6de.png)

As assumed above, the average load/generation is around 2200 MW through the year and should not show any significant "ups and downs" in the load curve. Same can be observed in the graph.

A constant ratio of hydro vs. geothermal **or** a fixed geothermal (600 MW) and "gap filling" hydro could be applied to this. Second option would consider the better flexibility of hydro to cover these demand drops and increases that you can observe (due to industry demand, I guess).

**Comment by alixunderplatz** [comment] 2018-05-15 14:02
... a final comment from me on this issue^^

![image](https://user-images.githubusercontent.com/25743609/40061343-03b7f8d8-5859-11e8-8254-6b137c6aed98.png)

**Comment by SNPerkin** [comment] 2019-10-21 21:47
Hey @alixunderplatz and @corradio, really cool project.

You've clearly made some effort trying to get data for Iceland over the last few years, particularly with the amper API and trying to 'reverse engineer' some kind of real-time data. It is a shame to not have Iceland on the map!

The reason that there isn't any Landsnet data on the ENTSO-E transparency portal is primarily due to Landsnet not being a part of the pan-European electricity market (despite being an ENTSO-E member).

Let me see if I can make some of the data available.

Kind regards,

Samuel
