### ISSUE TITLE
Inconsistent DK <-> SE data in real-time

### ISSUE THREAD

**Issue by Agazoth** [tmrowco/electricitymap#556] opened 2017-05-20 05:26 UTC
It seems like the swedish export disappeas for some datasets.
![20170520_072147-collage](https://cloud.githubusercontent.com/assets/15127301/26273301/a91f03ae-3d2d-11e7-9967-c6ea97dcd5d3.jpg)

**Comment by Agazoth** [comment] 2017-05-22 04:28
This seems to be a more general problem. Other countries show strange  readings as well, when Sweden is off.
![screenshot_20170522-062534](https://cloud.githubusercontent.com/assets/15127301/26292625/b90bee68-3eb7-11e7-9fc4-c0ffac365142.png)

**Comment by corradio** [comment] 2017-05-22 07:45
I think it's because the data is delayed from ENTSOE. Will keep an eye on this.
The display bug however should be fixed.

**Comment by Agazoth** [comment] 2017-06-02 05:20
Any news on this? It is still happening.

**Comment by corradio** [comment] 2017-06-02 05:47
It seems I've identified the problem. It occurs when ENTSOE sets future values to 0. They should be set to null if there are unknown. This causes our system to believe there's no exchange, and thus hides the arrows.

![image](https://cloud.githubusercontent.com/assets/1655848/26712504/7158ffe4-4767-11e7-9759-00cb5bb1bf21.png)

@Dalius-ENTSO-E can you help us here?

**Comment by Dalius-ENTSO-E** [comment] 2017-06-02 07:21
The problem is that SvK reports 0 values for the future hours and they do the same with some other data items, for example Actual Total load. I will check with SvK if they can change the way how they report data. Another option is that we can delay publications in the way to not publish future hours. We will check which option can be done faster.

**Comment by corradio** [comment] 2017-06-02 07:25
Thanks for the quick reply!

**Comment by corradio** [comment] 2017-09-04 06:49
Fixed as stated in #559. @Agazoth feel free to re-open if it happens again!

**Comment by corradio** [comment] 2017-09-06 08:17
Reopening as the issue still happens.
This screenshot was taken at 10:15 UTC+2 today:

![image](https://user-images.githubusercontent.com/1655848/30101422-8eb40a9a-92ec-11e7-8f8d-a6eb4a27e477.png)

**Comment by corradio** [comment] 2017-12-08 08:39
Here's a detailed issue:

The last line seems to be at 0
![image](https://user-images.githubusercontent.com/1655848/33756987-6bdcd4b6-dbf8-11e7-899a-e4ef2aa41e0b.png)

But a couple of minutes later, the numbers appear.
![image](https://user-images.githubusercontent.com/1655848/33757698-8e761a52-dbfb-11e7-94b1-3ef2b514cdc8.png)

This makes the data inconsistent in real-time, and improper carbon intensity numbers are detected.

@Dalius-ENTSO-E are you able to double check in ENTSOE's system as to why this discrepancy happens? Let me know if I can help, and thank you in advance for you help.

**Comment by jarek** [comment] 2017-12-10 13:25
Maybe it can be fudged by ignoring SE exchange data when it specifies 0 for first 15-30 minutes of the current hour? Will the system then keep and use the previous hour's data, like it seems to do with generation?

**Comment by corradio** [comment] 2017-12-10 17:07
Indeed we could code something like that. It's a bit of a hack though :)

**Comment by corradio** [comment] 2018-01-04 18:50
Closing as we don't use ENTSOE data anymore

**Comment by corradio** [comment] 2018-01-04 18:50
Closing as we don't use ENTSOE data anymore

**Closed by corradio** 2018-01-04 18:50 UTC
Labels: bug, parser
