### ISSUE TITLE
wind blowing and map colours

### ISSUE THREAD

**Issue by Francoue** [tmrowco/electricitymap#1050] opened 2018-01-30 15:25 UTC
Great map, full of useful info and easy to interact with. One question : the blowing of the wind appears differently according to map colours. If you take Germany (light yellow) France (light green) for example, you hardly see any wind blowing. Can it be improved or is it simply because there is so little of it ?

**Comment by corradio** [comment] 2018-01-30 15:27
I think this is a duplicate of #448

**Closed by corradio** 2018-01-30 15:27 UTC
