### ISSUE TITLE
Tidying up Turkey info

### ISSUE THREAD

**Issue by jzlcdh** [tmrowco/electricitymap#1312] opened 2018-04-07 19:31 UTC
This a bit picky and obviously is lowest priority but I thought I would note some minor points as I noticed them:

In the night time when I hover over the bar for solar it says we are generating ?% whereas that should be 0% (apart from possibly a tiny amount into the early evening from our single small CSP tower). 

And there is no battery storage yet (it is coming soon) and no pumped hydro storage (not likely in future as we have so many dams already so it would not be economic) so those should show zero not a question mark.

Also "available" is not quite right in phrases such as: "45% of emissions available in Turkey come from coal". It would read better something like: "Coal emitting 45% of greenhouse gas from electricity generation in Turkey"

**Comment by corradio** [comment] 2018-04-08 15:40
Hi @jzlcdh ,

The ?% vs 0% solar should be fixed now.
For the battery storage/pumped hydro, we should indeed set them to 0 by setting the associated capacities to 0 (feel free to submit a PR by editing the `zones.json` file in the `config` folder.
For your last question, the percentage shown is % of (generation + import + storage discharge). Saying "generation" only would be wrong. We've chose en say "available" to represent the fact that it's a % of everything that is available in the country (and a part of this is then exported / stored).
I agree the language could be improved though, but did not find anything better.

**Comment by alixunderplatz** [comment] 2018-04-09 12:01
🔎 Transparency platform for the Turkish electricity market:

https://seffaflik.epias.com.tr/transparency/index.xhtml

![image](https://user-images.githubusercontent.com/25743609/38496384-a2d65c20-3bfd-11e8-9c9a-e8f31dabdaea.png)


Maybe the [TR.py parser](https://github.com/tmrowco/electricitymap/blob/master/parsers/TR.py) could be switched to that site, which is also disclosing the same generation mix as Teias, so the source for generation and price (#1316) will be the same.
**Plus: Looks like they have an API!** (Check out web services on the left for documentation). The API portal link doesn't work for me though.

**Comment by alixunderplatz** [comment] 2018-04-09 12:53
I think I could have figured out a way to get the missing total solar generation 😃👍
Unfortunately, this only works for ex-post data and is therefore not available in real time.

The latest data right now is for 28 Feb 2018.

On the transparency portal, you'll find the renewable ex-post generation data.
https://seffaflik.epias.com.tr/transparency/uretim/yekdem/gerceklesen-uretim.xhtml

There is a graph below which shows a renewable breakdown except for solar. But the "total" graph shows these typical solar peaks. 

![image](https://user-images.githubusercontent.com/25743609/38498457-c9e7abfa-3c04-11e8-9978-9a882df5426c.png)

I downloaded some data and could underline the assumptions! 😸 
There also is a remaining generation during nighttime, maybe it is from some CSP projects or just an offset caused by something else that could be dismissed during nighttime.

![image](https://user-images.githubusercontent.com/25743609/38498728-ada41996-3c05-11e8-81ae-d4906f57f722.png)

**Comment by jzlcdh** [comment] 2018-04-09 12:58
Good work. The [only CSP](https://www.wikizero.com/en/Greenway_CSP_Mersin_Solar_Tower_Plant) we have is very small.

**Comment by alixunderplatz** [comment] 2018-04-09 13:15
allright, so this is another kind of offset then at night which is not caused by CSP.

@jzlcdh thanks for mentioning the site of EPIAS :) 👍 👍 👍

**Comment by jzlcdh** [comment] 2018-04-09 13:36
So maybe if you butter them up about their wonderful website they will answer all your questions. If you send any emails about the transparency platform to gorusleriniz.seffaflik@epias.com.tr and they don't reply in a reasonable time let me know so I can try to chase them up with the help of my Turkish teacher.

**Comment by jzlcdh** [comment] 2018-04-09 15:05
@corradio Afraid I am still seeing "?%" when hovering over the bar to the right of solar.

**Comment by corradio** [comment] 2018-04-09 15:09
@jzlcdh do you mean the "? % of installed capacity" ? Indeed this seems like a bug. I'll fix this

![image](https://user-images.githubusercontent.com/1655848/38505905-a31c2ee2-3c18-11e8-8073-fe28dca34cba.png)

**Comment by jzlcdh** [comment] 2018-04-09 15:11
Yes thanks

**Comment by corradio** [comment] 2018-05-04 14:42
@jzlcdh I think this issue if this has been solved.
Feel free to re-open if not.

**Closed by corradio** 2018-05-04 14:42 UTC
Labels: parser

**Comment by jzlcdh** [comment] 2018-05-04 15:26
@corradio Yes you are right to close it as it is a confusing mix now and at least some of it has been solved. I will check and reopen any bits which have not been solved as clearer separate (albeit probably tiny) issues.
